#!/bin/bash

set -e

go list -f '{{.Dir}}' -m | xargs -I {} go vet {}/...
go list -f '{{.Dir}}' -m | grep -v /cmd/ | xargs -I {} go tool gosec {}/...
go list -f '{{.Dir}}' -m | xargs -I {} go test {}/...
